services:
  playground.service.abstract_counting:
    class: PlaygroundBundle\Service\AbstractCountingService
    abstract: true

  playground.service.double_counting:
    class: PlaygroundBundle\Service\DoubleCountingService
    parent: playground.service.abstract_counting

  playground.service.triple_counting:
    class: PlaygroundBundle\Service\TripleCountingService
    parent: playground.service.abstract_counting

  playground.service.base_entity_manager:
    class: PlaygroundBundle\Service\BaseEntityManager
    arguments: [@doctrine.orm.entity_manager]
    public: false

  playground.service.table_manager:
    class: PlaygroundBundle\Service\TableManager
    parent: playground.service.base_entity_manager
    calls:
        - [setLogger, [@logger]]
        - [setTableRepository, [@playground.repository.table]]

  playground.service.chair_manager:
    class: PlaygroundBundle\Service\ChairManager
    parent: playground.service.base_entity_manager
    calls:
        - [setLogger, [@logger]]
        - [setChairRepository, [@playground.repository.chair]]

  playground.service.class_name_manager:
    class: PlaygroundBundle\Service\ClassNameManager
    arguments:
      services: [@playground.service.table_manager, @playground.service.chair_manager]


