services:
  playground.service.abstract_counting:
    class: PlaygroundBundle\Service\AbstractCountingService
    abstract: true

  playground.service.double_counting:
    class: PlaygroundBundle\Service\DoubleCountingService
    parent: playground.service.abstract_counting

  playground.service.triple_counting:
    class: PlaygroundBundle\Service\TripleCountingService
    parent: playground.service.abstract_counting

  playground.service.base_entity_manager:
    class: PlaygroundBundle\Service\BaseEntityManager
    arguments: [@doctrine.orm.entity_manager]
    public: false

  playground.service.table_manager:
    class: PlaygroundBundle\Service\TableManager
    parent: playground.service.base_entity_manager
    calls:
        - [setLogger, [@logger]]
        - [setTableRepository, [@playground.repository.table]]

  playground.service.chair_manager:
    class: PlaygroundBundle\Service\ChairManager
    parent: playground.service.base_entity_manager
    calls:
        - [setLogger, [@logger]]
        - [setChairRepository, [@playground.repository.chair]]

  playground.service.class_name_manager:
    class: PlaygroundBundle\Service\ClassNameManager
    arguments:
      services: [@playground.service.table_manager, @playground.service.chair_manager]

  playground.service.stdout_renderer:
    class: PlaygroundBundle\Service\StdoutRenderer
    factory_class: PlaygroundBundle\Service\Factory\RendererFactory
    factory_method: create
    arguments:
        - stdout

  playground.service.file_renderer:
    class: PlaygroundBundle\Service\FileRenderer
    factory_class: PlaygroundBundle\Service\Factory\RendererFactory
    factory_method: create
    arguments:
        - file

  playground.service.integer_storage:
    class: PlaygroundBundle\Service\IntegerStorage
    tags:
      - { name: simple_storage }

  playground.service.float_storage:
    class: PlaygroundBundle\Service\FloatStorage
    tags:
      - { name: simple_storage }


